name: main branch deployment
on:
  [ push, workflow_dispatch ]
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    name: deploy to aws
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: assume deploy role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::467222377375:role/github-actions
        aws-region: us-east-1
    
    - name: cdk deploy
      uses: .github/actions/cdk-deploy